ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS verification_token_hash CHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS verification_expires_at TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS session_version INT NOT NULL DEFAULT 0;
